version: '3.8'

services:
  user_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user_db:/var/lib/postgresql/data

  product_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"
    volumes:
      - product_db:/var/lib/postgresql/data

volumes:
  user_db:
  product_db: